FROM node:18

WORKDIR /app

# Copy only package files first
COPY package*.json ./

# Install dependencies INSIDE container
RUN npm install --legacy-peer-deps --no-audit --no-fund

# Then copy rest of code
COPY . .

# Run app
CMD ["npm", "run", "dev"]